version: '3.8'

services:
  bot:
    build: .
    container_name: bobot-financeiro
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
